# Generated by Django 5.1.4 on 2025-01-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('author_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
