# Generated by Django 5.1.4 on 2025-01-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tweets', models.TextField()),
                ('like_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
